# ArrowArsenal Config

# Version
version: 1.0

# Settings
settings:

  # Should extra information be logged? (Only useful for bug testing)
  debug: false

  # What locale should be used when sending messages?
  locale: en

  # What prefix should be used for the plugin? | {name} is replaced with the plugin name
  prefix: "&f[&r&b{name}&r&f]"

  # Should a special gui be used for arrow selection?
  use-select-gui: true

  # What name should be used for the arrow selection menu?
  arrow-select-menu-name: "Arrow Select"

  # What name should be displayed on the button for the next page in the arrow select menu?
  next-page-name: "&2Next Page"

    # What name should be displayed on the button for the previous page in the arrow select menu?
  previous-page-name: "&4Previous Page"