# ArrowArsenal Config

# Settings
settings:

  # Should extra information be logged? (Only useful for bug testing)
  debug: false

  # What locale should be used when sending messages?
  locale: en

  # What prefix should be used for the plugin? | {name} is replaced with the plugin name
  prefix: "&f[&r&b{name}&r&f]"

  # Should a special gui be used for arrow selection?
  use-select-gui: true