name: ${project.name}
version: ${project.version}
description: ${project.description}
author: SonarBeserk

main: me.sonarbeserk.arrowarsenal.ArrowArsenal

permissions:
  arrowarsenal.notify.files:
    description: notifies players with this permission of files being out of date
    default: op
  arrowarsenal.commands.reload:
    description: allows use of the reload subcommand
    default: op
  arrowarsenal.commands.disable:
    description: allows use of the disable subcommand
    default: op
  arrowarsenal.commands.enable:
    description: allows use of the disable subcommand
    default: op
  arrowarsenal.commands.select:
    description: allows use of the select subcommand
    default: op

commands:
  arrowarsenal:
    description: master command system for the plugin
    usage: "ArrowArsenal Usage: /arrowarsenal help"
    aliases: [aa]